name: pcb-artifacts-Module440JB

on:
  push:
    paths:
    - 'Module440JB/**.sch'
    - 'Module440JB/**.kicad_pcb'
    - '.github/workflows/pcb-artifacts-esp32-controller.yaml'
    - '**.kibot.yaml'
  pull_request:
    paths:
    - 'Module440JB/**.sch'
    - 'Module440JB/**.kicad_pcb'
    - '.github/workflows/pcb-artifacts-esp32-controller.yaml'
    - '**.kibot.yaml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  repo: stuartpittaway/diyBMSv4
  main_branch: master

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest

    steps:
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        git lfs install

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Update the PCBs with on default branch with git hash
      if: steps.extract_branch.outputs.branch == env.main_branch
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"    
        echo "ref: ${{ github.ref }}"
        echo "default: ${{ env.default }}"
        sed -i "s!<<hash>>!${COMMIT}!" Module440JB/Module440JB.kicad_pcb

    - name: Update the PCBs with the git hash and BETA.
      if: steps.extract_branch.outputs.branch != env.main_branch
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!BETA-${COMMIT}!" Module440JB/Module440JB.kicad_pcb

    - name: Prepare artifacts
      run: |
        cd Module440JB
        rm -rf export/
        kibot -c ../config-2layer.kibot.yaml -e Module440JB.sch -b Module440JB.kicad_pcb -d export

    # Splitting this out to ensure a failed kibot run will mark a check as failed.
    - name: Prepare Gerbers artifact
      run: |
        cd Module440JB/export/gerbers
        zip -r -j ../Module440JB_gerbers.zip *        

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.repository != env.repo)
      with:
        name: Module440JB_gerbers
        path: Module440JB/export/Module440JB_gerbers.zip

    - name: Commit files
      if: github.event_name == 'push' && github.repository == env.repo
      run: |
        git add -f Module440JB/export
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git commit -m "CI: pcb-artifacts-Module440JB"
        git push -u origin
